### PR TITLE
Start transition to quartodoc

### PR DESCRIPTION
**Pull request by juliasilge**

### CODE REVIEW

**Comment by juliasilge** [comment]
@machow I am seeing this error when I try to run `quartodoc build`, and I'm not sure what I changed since it was working earlier:

```
TypeError: dataclass_transform() got an unexpected keyword argument 'field_specifiers'
```

Does that look familiar?

**Comment by juliasilge** [comment]
@machow If I install ipython 8.12.0 locally, then doing `pip-compile --extra=doc --extra=test --output-file=- setup.cfg` still puts 8.13.2 into `requirements/dev.txt`. I think it must be something else in `setup.cfg` that is causing that version of ipython to be chosen.

- How do I find out what is choosing that newer version of ipython?
- Or would it be appropriate for me to use something like `ipython<=8.12.0` in `setup.cfg`? Would I put that under "docs"?

**Comment by juliasilge** [comment]
I did not add any links to things like `fsspec.filesystem` because there is [not much](https://filesystem-spec.readthedocs.io/en/latest/api.html#user-functions) available.

**Comment by juliasilge** [comment]
[This is looking pretty good](https://pr-198--pins-python.netlify.app/reference/), I think! 

@machow here are some blockers to moving forward at this point:

🎯 When using interlinking, the generated links look like regular text instead of code:

Screenshot 2023-05-25 at 1 07 33 PM

We need them to look like ``[`board_folder()`](/reference/board_folder.html)``

🎯 I'm having trouble using interlinks for parameters:

Screenshot 2023-05-25 at 1 40 41 PM

**Comment by juliasilge** [comment]
Will close #186 if we can get interlinks to look OK

**Comment by machow** [comment]
Shoot--I think that not generating a link inside the parameter description is a bug. We currently sanitize the output, so that symbols like `|` won't break the markdown table, but this ends up also screwing up the interlink syntax...

Opened an issue here https://github.com/machow/quartodoc/issues/172

**Comment by machow** [comment]
> I feel fuzzy on what adding documentation for BaseBoard gets us that isn't already there in the sidebar. Can you tell me a little bit more about what we might document on a page like that?

It feels like some kind of connective tissue is missing. There are a bunch of function/method names on the page, but as a person who will be interacting with an object, it's surprising the object type itself is not documented / named.

The idea that some functions return an object, and then some other things that look like functions are actually methods on an object--without the object there--feels like it's missing what l see in the repl / various informative displays.

image

**RE "what we might document on a page like that?"**

I think this situation is similar to documenting an S4 / R6 class, so just having the type name on the sidebar will reinforce where `pin_read()` lives. (On the page itself we could just emphasize that this is the main object people interact with in the package; repeat some of the other constructor stuff).

## Alternatively

If we are very loud in saying some things construct a BaseBoard instance, some things are methods, we might be able to get the point across.

**Comment by machow** [comment]
Thanks for these changes!

Do you mind saying more about when you think removing the sidebar makes things more clear? I'm onboard with any changes, and want to make sure I capture the strategy (eg why removing the sidebar might provide clarity here compared to the [vetiver api docs](https://rstudio.github.io/vetiver-python/latest/reference/)). 

It seems like the big factor might just be the size of the pins api docs (since it's just documentation around roughly a single class, with only a few methods)?

**Comment by machow** [comment]
TODO:

* change "Function Reference" to Reference
* remove dev branch of quartodoc (should be on main)

**Comment by juliasilge** [comment]
Also TODO here is to switch to the regular `/docs` folder, and replace the existing docs.

**Comment by machow** [comment]
Okay, finally wrapped the last TODO pieces w/ @isabelizimm , merging!

**Pull request merged**
