### PR TITLE
Support Python 3.12

### PR DESCRIPTION
**Pull request by nathanjmcdougall**

### CODE REVIEW

**Comment by nathanjmcdougall** [comment]
I note that the `CI / Tests` pipeline hasn't triggered, but it would be pretty important to run this before merging.

**Comment by isabelizimm** [comment]
I appreciate you turning these tests on 🚀 

And, to clarify why `CI/Tests` does not run immediately since forks don't have access to the secrets used to test across all the backends. On initial PR creation from a fork, you'll get the secret-less versions of the tests until I tell git to run all the cloud-based tests. No action needed on your part! That step is part of my review process 💭

**Comment by nathanjmcdougall** [comment]
This seems to be related to the issue:
https://github.com/jdidion/atropos/issues/135

**Comment by isabelizimm** [comment]
Going off historical commits/PRs, it looks like there was a [point in time where the latest version of `adlfs` was broken](https://github.com/rstudio/pins-python/pull/173) for our CI, although I don't have insight into exactly what that failure was. I agree the pin is pretty safe since it is just for testing! I have a slight preference to set it `>=2024.4.1`, which feels less surprising than pinning a specific version...which I know is not how it was 🙈 but that way we'll hopefully not end up in a situation with a 2 year old, potentially stale version again.

**Comment by nathanjmcdougall** [comment]
I agree, that's better, I've made that change.

**Review by isabelizimm — APPROVED** [review]
beautiful! 🤩🚀

**Pull request merged**
