### PR TITLE
Feat rsc code block

### PR DESCRIPTION
**Pull request by machow**
Partially address #114 , but adding a python code snippet for retrieving the pin.

### CODE REVIEW

**Comment by machow** [comment]
rebased on top of main

**Comment by machow** [comment]
@sellorm @kellobri -- do you mind double checking that this is enough to match the R behavior (I'll leave Mark's original issue open, since it raises a broader issue about the code block + interop!)

https://colorado.rstudio.com/rsc/connect/#/apps/6e1b8ea7-aafb-462a-b644-d4a62951ec85

**Comment by kellobri** [comment]
Yes! This is what I would expect 👍

**Comment by machow** [comment]
thanks!

**Comment by sellorm** [comment]
I know I'm late to this one -- and I know this is obvious to us -- but it would be great if this code snippet was identified as being Python as opposed to R. Just to avoid any unnecessary user confusion.

Maybe change the `<h3>Code</h3>` to `<h3>Python Code</h3>` or something like that.

On Connect instances with R and Python users, having code snippets that aren't clearly identified may cause some user confusion.

**Pull request merged**
